In [1]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import tensorflow as tf

C:\Users\d822u-r012\AppData\Local\Continuum\anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
3. # a rank 0 tensor; a scalar with shape [],
[1., 2., 3.] # a rank 1 tensor; a vector with shape [3]
[[1., 2., 3.], [4., 5., 6.]] # a rank 2 tensor; a matrix with shape [2, 3]
[[[1., 2., 3.]], [[7., 8., 9.]]] # a rank 3 tensor with shape [2, 1, 3]

[[[1.0, 2.0, 3.0]], [[7.0, 8.0, 9.0]]]

In [3]:
#构建计算图 (tf.Graph)。
#运行计算图 (tf.Session)。
a = tf.constant(3.0, dtype=tf.float32)
b = tf.constant(4.0) # also tf.float32 implicitly
total = a + b
print(a)
print(b)
print(total)

Tensor("Const:0", shape=(), dtype=float32)
Tensor("Const_1:0", shape=(), dtype=float32)
Tensor("add:0", shape=(), dtype=float32)


In [4]:
#TensorFlow 提供了一个名为 TensorBoard 的实用程序,TensorBoard 的诸多功能之一是将计算图可视化
writer = tf.summary.FileWriter('aasda')
writer.add_graph(tf.get_default_graph())
#tensorboard --logdir C:\Users\d822u-r012\Desktop\TensorFlow\aasda

In [6]:
sess = tf.Session()
print(sess.run(total))

7.0


In [7]:
vec = tf.random_uniform(shape=(3,))
out1 = vec + 1
out2 = vec + 2
print(sess.run(vec))
print(sess.run(vec))
print(sess.run((out1, out2)))

[0.66871476 0.45719516 0.8827268 ]
[0.49465024 0.30356348 0.74212694]
(array([1.6470777, 1.757906 , 1.8816948], dtype=float32), array([2.6470776, 2.757906 , 2.8816948], dtype=float32))


In [8]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
z = x + y

In [9]:
print(sess.run(z, feed_dict={x: 3, y: 4.5}))
print(sess.run(z, feed_dict={x: [1, 3], y: [2, 4]}))

7.5
[3. 7.]


In [10]:
my_data = [
    [0, 1,],
    [2, 3,],
    [4, 5,],
    [6, 7,],
]
slices = tf.data.Dataset.from_tensor_slices(my_data)
next_item = slices.make_one_shot_iterator().get_next()

In [11]:
features = {
    'sales' : [[5], [10], [8], [9]],
    'department': ['sports', 'sports', 'gardening', 'gardening']}

department_column = tf.feature_column.categorical_column_with_vocabulary_list(
        'department', ['sports', 'gardening'])
department_column = tf.feature_column.indicator_column(department_column)

columns = [
    tf.feature_column.numeric_column('sales'),
    department_column
]

inputs = tf.feature_column.input_layer(features, columns)

In [12]:
var_init = tf.global_variables_initializer()
table_init = tf.tables_initializer()
sess = tf.Session()
sess.run((var_init, table_init))

(None, None)

In [13]:
print(sess.run(inputs))

[[ 1.  0.  5.]
 [ 1.  0. 10.]
 [ 0.  1.  8.]
 [ 0.  1.  9.]]


# linear model

In [ ]:
x = tf.constant([[1], [2], [3], [4]], dtype=tf.float32)
y_true = tf.constant([[0], [-1], [-2], [-3]], dtype=tf.float32)

# construct graph

In [15]:
linear_model = tf.layers.Dense(units=1)
y_pred = linear_model(x)

# run graph

In [16]:
writer = tf.summary.FileWriter('linear')
writer.add_graph(tf.get_default_graph())

In [17]:
#訓練してない
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

print(sess.run(y_pred))

[[-0.15856695]
 [-0.3171339 ]
 [-0.47570086]
 [-0.6342678 ]]


In [18]:
loss = tf.losses.mean_squared_error(labels=y_true, predictions=y_pred)
print(sess.run(loss))

2.1029067


In [19]:
optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(loss)

In [20]:
for i in range(100):
  _, loss_value = sess.run((train, loss))
  print(loss_value)

2.1029067
1.5257823
1.1249299
0.8463906
0.6527248
0.5179528
0.42404854
0.35850382
0.31263947
0.28043324
0.2577064
0.24155936
0.22998008
0.22157264
0.21536818
0.21069467
0.20708553
0.2042172
0.20186505
0.19987324
0.19813362
0.19657113
0.19513363
0.19378504
0.19250011
0.19126162
0.1900573
0.18887883
0.1877203
0.18657762
0.185448
0.18432947
0.18322057
0.18212043
0.1810283
0.17994371
0.1788663
0.17779578
0.17673205
0.17567486
0.17462417
0.17357981
0.17254184
0.17151013
0.1704846
0.16946527
0.168452
0.16744485
0.16644369
0.16544856
0.16445932
0.16347608
0.16249867
0.16152708
0.16056134
0.15960138
0.15864713
0.15769863
0.15675578
0.15581855
0.15488693
0.15396088
0.15304035
0.15212534
0.15121585
0.15031177
0.14941305
0.14851971
0.14763176
0.14674911
0.1458717
0.14499956
0.14413263
0.14327088
0.14241432
0.14156282
0.14071642
0.13987508
0.1390388
0.13820754
0.1373812
0.13655981
0.13574333
0.13493177
0.13412502
0.1333231
0.13252601
0.13173366
0.13094603
0.13016313
0.1293849
0.12861134
0.12784237

In [21]:
print(sess.run(y_pred))

[[-0.5636499]
 [-1.273127 ]
 [-1.982604 ]
 [-2.6920812]]
